### ISSUE TITLE
hi, can't compile as String.h is missing...

### ISSUE THREAD

**Issue by greatflyers** [SeeedJP/WioLTEforArduino#30]
hi, can't compile as String.h is missing...

**Comment by ytsuboi** [comment]
Hi @greatflyers 
This library is for SeeedJP STM32 Boards.
Please add `http://www.seeed.co.jp/package_SeeedJP_index.json` to additional board manager URL, and install `SeeedJP STM32 Boards`. By the historical issue, Seeed Japan branch released and maintain this version for customers in Japan.

<img width="761" alt="image" src="https://user-images.githubusercontent.com/246704/82569497-49594c00-9bbb-11ea-8301-2d8253882419.png">

For now, we are only providing [documents](https://seeedjp.github.io/Wiki/Wio_LTE_for_Arduino/Home-ja.html) in Japanese. I will consider to provide documentation in English.
