### ISSUE TITLE
Wio LTE Cat.1のスケッチ例

### ISSUE THREAD

**Issue by toyowata** [SeeedJP/WioLTEforArduino#33]
Wio LTE Cat.1で手順通りにインストールしましたが、サンプルのスケッチがボード用になっていない気がします。
ボードパッケージは、1.4.0です。

![sample](https://user-images.githubusercontent.com/4926755/90852125-a11d7400-e3b1-11ea-8d93-dfd93f5142db.jpg)

**Comment by mnakai3** [comment]
Wio LTE for Arduinoライブラリは追加されたでしょうか？
https://seeedjp.github.io/Wiki/Wio_LTE_for_Arduino/AddWioLTELibrary-ja.html

![image](https://user-images.githubusercontent.com/60082798/90852968-d88d2000-e3b3-11ea-8ace-225ac15915f4.png)

**Comment by toyowata** [comment]
@mnakai3 該当のライブラリを入れたら、サンプルスケッチが追加されました。ありがとうございます。
