### ISSUE TITLE
LED Documentation & Battery Issue

### ISSUE THREAD

**Issue by trawinlegacy** [SeeedJP/WioLTEforArduino#37]
**What do the LED lights indicate?** Ie: the single green light and the two red lights.

**Before plugging in the battery** while in normal mode,1 red and 1 green LED would remain solid while the other red LED would blink. Both the red LEDs would turn off when in DFU mode.

**After plugging in the battery**, both red LEDs have remained off at all times. The green LED was solid at first (meaning charging?) then turned off after 30 mins (done charging?) and would blink when the battery is disconnected.

Also since plugging in the battery, when I set the device to DFU mode I can see “STM32 BOOTLOADER” in the device manager and upload code but when I turn it back to normal mode the Arduino IDE cannot find it’s COM port when opening the serial monitor. In normal mode I cannot find the board in device manager. Until connecting the battery this was not a problem…

**What do I need to do to fix this**? Is there better documentation on all of the LEDs and the buttons than what is on this link? [](https://wiki.seeedstudio.com/Wio_LTE_Cat.1/#resource
)
Device: WIO LTE US VERSION - 4G, CAT.1 board, v1.1.

**Comment by ytsuboi** [comment]
Hi @trawinlegacy 
For hardware issues, please use our [forum](https://forum.seeedstudio.com/c/products/wio-series/17). This issue on GitHub WioLTEforArduino repository is for software issues of WioLTEforArduino software.
