### ISSUE TITLE
Setup jaで混乱したこと

### ISSUE THREAD

**Issue by kekyo** [SeeedJP/WioLTEforArduino#4]
1. [Wio LTEのモード切替とデバイスドライバーの動作確認 の 通常モード](https://github.com/SeeedJP/WioLTEforArduino/wiki/Setup-ja#%E9%80%9A%E5%B8%B8%E3%83%A2%E3%83%BC%E3%83%89) の説明で、「RSTボタンをクリックすると、DFUモードで再起動します」の"DFUモード"は通常モードの間違い？
2. DFUモードの説明部分は箇条書きにしたほうがいいと思います。以下一例:

  ```
マイコンをDFUモードで起動して、デバイスマネージャーの"ユニバーサルシリアルバスデバイス"配下に"STM32 BOOTLOADER"が表示されていれば正常です。

  * "ほかのデバイス"配下に"STM32 BOOTLOADER"と表示されている場合は、Wio Tracker LTEボードを追加してください。
  * "ユニバーサルシリアルバスコントローラー"配下に"STM Device in DFU Mode"と表示されている場合は、WinUSBデバイスドライバーに切り替えを実施してください。

通常モード

ボタンを押さずにUSBコネクターにUSBケーブルを接続すると、マイコンが通常モードで起動します。 すでにUSBケーブルが接続されている場合は、RSTボタンをクリックすると、通常モードで再起動します。 デバイスマネージャーの"ポート"配下に"STMicroelectronics Virtual COM Port"が表示されていれば正常です。

* "ほかのデバイス"配下に"STM32 Virtual ComPort in FS Mode"と表示されている場合は、Virtual COM Portデバイスドライバーのインストールを実施してください。
  ```

3. プログラムの書き込みで、basic/LedSetRGBを開く、の部分はスクリーンショットがあったほうがいいと思いました（自分はGitHubからコードをコピペしようとした）

**Comment by matsujirushi** [comment]
1. 間違いでした。訂正しました。
2. このままで様子見します。（当初は箇条書きでしたが変更しました）
3. 追加します。

**Comment by matsujirushi** [comment]
3. 追加しました。
