### ISSUE TITLE
Windowsのユーザーディレクトリにスペースが入っていると書き込みに失敗する

### ISSUE THREAD

**Issue by ciniml** [SeeedJP/WioLTEforArduino#6]
ライブラリの不具合ではなく、ボードパッケージ内のバッチファイルの問題ですが、どこに言ったらいいかわからなかったので、とりあえずここに書いておきます。

### 現象
Arduino IDEでアップロードしようとするとDFU以前の問題でエラー発生

```
C:\Users\Kenta IDA\AppData\Local\Arduino15\packages\Seeeduino\tools\stm32_dfu_upload_tool\1.0.0/win/dfu_upload.bat 0 0483:df11 C:\Users\KENTAI~1\AppData\Local\Temp\arduino_build_262717/SMSSend.ino.bin 0x8000000 
DFU begin
'C:\Users\Kenta' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
DFU end
```
実行されているコマンドを見る限り、ユーザー名にスペースが入っているのが問題の模様

### 解決方法

`%LOCALAPPDATA%\arduino15\packages\Seeeduino\tools\stm32_dfu_upload_tool\1.0.0\win\dfu_upload.bat`のコマンドラインをダブルクォートで囲む

```
@echo off

echo DFU begin

"%~dp0/dfu-util-0.8-mingw32/dfu-util.exe" -d %2 -a %1 -D "%3" -s %4 -R

echo DFU end
```

一応これで書き込めるようになりました。

**Comment by matsujirushi** [comment]
Seeed_Platformにissue上げました。
https://github.com/Seeed-Studio/Seeed_Platform/issues/6

**Comment by ciniml** [comment]
ありがとうございます。
SeeedのボードのArduino IDE対応周りはこのリポジトリなんですね。
次からはそちらに投げるようにします。

**Comment by matsujirushi** [comment]
https://github.com/Seeed-Studio/Seeed_Platform/issues/6#issuecomment-343145789
